comparisonmode = 'yes' #'yes' (default) or 'no', for multiple workouts, choose yes, if only interested in one, then 'no' might be better. Use 'yes' if not sure. 
testmode = 'no'  #'yes' or 'no' (default), used to check time_step_threshold and ele_gain_threshold, or to see what section settings you need for plotting...
plotonlysection = 'no' #'yes' or 'no' (default), used to plot only one section of the training
climbspecific = 'no' #'yes' or 'no' (default), if 'yes' (use along with plotonlysection = 'yes') then prepares a standard climb diagram and cumulative elevation gain diagram, plus calculates average gradient and VAM
section = [34.616,60.52] #give the ranges (in km) of the section you want to analyse
slope_slice = 1. #length of a slope slice (resolution of gradient diagrams)
atl_timeconstant = 7. #time constant used when calculating ATL (for the Performance Management Chart, default is 7.)
ctl_timeconstant = 42. #time constant used when calculating CTL (for the Performance Management Chart, default is 42.)
time_step_threshold = 0.003 #in hour, used when calculating the moving speed (set for GARMIN Edge 500)
ele_gain_threshold = 3 #threshold setting what will be counted as a climb (3 meter is default)
gears_front= [50,34] #front chainrings
gears_rear = [11,12,13,14,15,17,19,21,24,28] #rear cassette
wheel_circ = 2096 #wheel circumference in mm
bins_hrzones = [45,118,149,161,168,180,184,191,198,210] #definition of HR Zones (0,1,2,3,4,5a,5b,5c,6 according to Joe Friel)
bins_speed_min = 0 #histogram parameters (min, max, and binsize)
bins_speed_max = 75
bins_speed_step = 1
bins_hr_min = 80
bins_hr_max = 200
bins_hr_step = 1
bins_cad_min = 1
bins_cad_max = 160
bins_cad_step = 1
bins_grad_min = -19.75
bins_grad_max = 19.75
bins_grad_step = 0.5
plots_speed_min = 0 #parameters for the 3Dplots (min, and max)
plots_speed_max = 75
plots_hr_min = 80
plots_hr_max = 200
plots_cad_min = -5
plots_cad_max = 160
plots_grad_min = -19.75
plots_grad_max = 19.75